### ISSUE TITLE
Flashlight flashing (not how it should)

### ISSUE THREAD

**Issue by parcel31u** [planetguy32/Gizmos#15]
The flashlight is constantly flashing, going into a dark cave will cause the screen to go black then light up, then black again.

**Comment by planetguy32** [comment]
Flashlights set a glowing block that decays soon after. It's ugly because the logic only happens server-side, since I couldn't find a client-side callback to clean up the blocks. Ideally there would be a client-side callback to erase the blocks after a tick, but even the existing system might look better if the blocks persisted a few ticks longer.

**Comment by planetguy32** [comment]
Released in v3.3.
